version: '3.8'

services:
  data-anonymization:
    build: .
    container_name: data-anonymization-service
    ports:
      - "8000:8000"
    volumes:
      # 持久化存储模型文件
      - ./models:/app/models:ro
      # 持久化日志
      - ./logs:/app/logs
      # 可选：挂载数据目录用于批量处理
      - ./data:/app/data:ro
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=-1
      - TF_CPP_MIN_LOG_LEVEL=2
      - TF_ENABLE_ONEDNN_OPTS=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # 可选：添加 Nginx 反向代理
  nginx:
    image: docker.xuanyuan.me/nginx:alpine
    container_name: data-anonymization-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - data-anonymization
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: data-anonymization-network
